### ISSUE TITLE
gifs not working for node v 10

### ISSUE THREAD

**Issue by udaypatial** [sergueyarellano/datmouth#23]

**Comment by sergueyarellano** [comment]
Do we want to give support to node 10? it uses promises as experimental.

The package we are using to display gifs is [term-img](https://www.npmjs.com/package/term-img ) and it is supposed to work with node > 8. Can you check this out? :)

**Comment by sergueyarellano** [comment]
Won't fix this since supporting node 10.19 I think it's good. Otherwise we have to implement requests by ourselves, and I feel that would be reinventing the wheel
